---
title: "Untitled"
output:
  pdf_document: default
  html_document:
    df_print: paged
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Study

```{r config, include=FALSE}
library(Rblpapi)
library(TTR)
library(PerformanceAnalytics)
library(PortfolioAnalytics)

# define Bloomberg tickers

tickers <- c(".DSTRAT Index", "TFCFR1E LX Equity", "MLAQSEI ID Equity",
             "TBWLSIE ID Equity", "BLWEERE ID Equity",
             "SXXR Index", "SPTR500N Index", "SPTRNE Index", "SPXUXEN Index",
             "EECBDEPO Index", "FDFD Index")


# define study periods
periods <- c(as.Date("2018-12-31"), as.Date("2018-02-27"), as.Date("2016-08-09"))


# connect to Bloomberg and download datas
opt <- c("periodicitySelection"="DAILY",
         "nonTradingDayFillOption"="ACTIVE_DAYS_ONLY",
         "nonTradingDayFillMethod"="PREVIOUS_VALUE")

con <- blpConnect()

prices <- bdh(tickers, "PX_LAST", min(periods), options = opt)

blpDisconnect(con)


# tidy data to xts and carry froward missing values
prices <- lapply(prices, function(x) xts(x[,2], x[,1]))
prices <- do.call(merge, prices)
prices <- na.locf(prices)

# rename columns
colnames(prices) <- c("SPhEur", "EuOn", "UsOn", "Dharma", "Q-Cap", "Quest", 
                      "Trium", "BlackLong", "Stoxx", "SP", "SPEur")

# calc Interest rates Indexes
days= c(0, diff(.indexDate(prices)))

prices$UsOnIdx <- 1 + (lag(prices$UsOn, 1) * days / 25200)
prices$EuOnIdx <-  1 + (lag(prices$EuOn, 1) * days / 25200)

prices$UsOnIdx[1] <- 1
prices$EuOnIdx[1] <- 1

prices$UsOnIdx <- cumprod(prices$UsOnIdx)
prices$EuOnIdx <- cumprod(prices$EuOnIdx)

# reorder columns
prices <- prices[, c(4:11, 1, 12, 13, 2 ,3 )]

# calc returns ad carry forward
returns <- ROC(prices[,1:11])
returns[1,] <- 0
returns <- na.locf(returns)

# plot rates indexes
plot(exp(cumsum(returns$EuOnIdx))-1)
plot(exp(cumsum(returns$UsOnIdx))-1)


```

### some datas 

datas:
## Risk return

```{r, echo=FALSE}

per <- 1
per <- periods[per]
per <- paste(per,"/")

mainIdx  <- returns[paste(periods[1],"/"), "Dharma"]
allIdx   <- returns[paste(periods[1],"/"), 1:9]
oneBench <- returns[paste(periods[1],"/"), 6]
twoBench <- returns[paste(periods[1],"/"), c(6, 8)]
riskFree <- prices [paste(periods[1],"/"), "EuOn"] / 25200



SharpeRatio(allIdx, 
            oneBench,
            p=0.95)


table.AnnualizedReturns(allIdx,
                        riskFree,
                        scale= 252,
                        digits= 4)

table.Arbitrary(allIdx,
                metrics= c("mean", "sd"))


# table.Autocorrelation(allIdx, digit=4)

# table.CalendarReturns(returns[paste(periods[3],"/"), 1], digit=4) # only monthly

# t(table.CaptureRatios(allIdx, 
#                      oneBench, 
#                      digits=4))

t(table.UpDownRatios(allIdx, 
                     oneBench, 
                     digits=4))


t(table.Correlation(allIdx, 
                    oneBench))

table.Distributions(allIdx)

table.DownsideRisk(allIdx,
                   ci=0.95, scale=252, p=0.99, 
                   digits=4, MAR = 0.05/252,
                   Rf=riskFree)

table.Drawdowns(allIdx,
                top=5, digits=4)

table.DrawdownsRatio(allIdx,
                     Rf=mean(riskFree),
                     scale=252, digits=4)

table.HigherMoments(allIdx,
                    Rb=oneBench,
                    Rf=riskFree,
                    scale=252, digits=4,
                    method="moment")

table.InformationRatio(allIdx,
                       Rb=oneBench,
                       scale=252, digits=4)

table.ProbOutPerformance(mainIdx,
                         oneBench,
                         period_length=c(1,30,200))


table.RollingPeriods(allIdx, 
                     periods=c(20,50,200))


table.SFM(allIdx,
          oneBench,
          Rf=riskFree,
          scale=252, digits=4)

table.SpecificRisk(allIdx,
                   oneBench,
                   Rf=mean(riskFree),
                   digits=4)

table.Stats(allIdx,
            ci=0.95, digits=4)

table.Variability(allIdx,
                  digits=4)

TotalRisk(allIdx,
          oneBench,
          Rf=riskFree)

TrackingError(allIdx,
              oneBench)

```




```{r datas, echo=TRUE}



AdjustedSharpeRatio(mainIdx,
                    riskFree)



AppraisalRatio(mainIdx, 
               oneBench, 
               mean(riskFree), 
               method="modified") # "appraisal", "alternative"

AverageDrawdown(allIdx)
library(xtable)
print(xtable(AverageDrawdown(allIdx)))

AverageLength(allIdx)
AverageRecovery(allIdx)

BernardoLedoitRatio(allIdx)

BetaCoVariance(allIdx, allIdx)
BetaCoSkewness(allIdx, allIdx)
BetaCoKurtosis(allIdx, allIdx)


BurkeRatio(allIdx,
           mean(riskFree),
           modified=FALSE) # TRUE

CalmarRatio(allIdx, scale=252)
SterlingRatio(allIdx, scale=252, excess=0.1)

# CAPM functions a bit disregarder now
CAPM.alpha(allIdx, 
           oneBench,
           riskFree)

CAPM.beta(allIdx, 
          oneBench,
          riskFree)

CAPM.CML.slope(oneBench,
               riskFree)

CAPM.SML.slope(oneBench,
               riskFree)


CAPM.CML(allIdx,
         oneBench,
         riskFree)


CAPM.RiskPremium(allIdx,
                 riskFree)

CAPM.dynamic(allIdx, 
             oneBench, 
             riskFree,
             returns[paste(periods[1],"/"), 4:5]) # fake Z facrot (public info not directly linked, ie US10y CPI etc...)

CAPM.epsilon(allIdx, 
             oneBench, 
             mean(riskFree))


CAPM.jensenAlpha(allIdx, 
                 oneBench, 
                 mean(riskFree))


CDD(returns, weight= NULL, p= 0.95)

length(mainIdx)
cb <- clean.boudt(mainIdx, alpha=0.01, trim=0.001)
length(cb[[1]])

CoSkewnessMatrix(allIdx)
CoKurtosisMatrix(allIdx)
CoVariance(allIdx,
           oneBench)
CoSkewness(allIdx,
           oneBench)
CoKurtosis(allIdx,
           oneBench)

M3.MM(allIdx, as.mat=FALSE, unbias=TRUE)
M4.MM(allIdx, as.mat=FALSE)


DownsideDeviation(allIdx,
                  MAR=0.0)
DownsidePotential(allIdx,
                  MAR=0.0)
SemiDeviation(allIdx)
SemiVariance(allIdx)

DownsideFrequency(allIdx, MAR=0)

DRatio(allIdx)

DrawdownDeviation(allIdx)

#Drawdowns(returns[paste(periods[3],"/"), 1])

#findDrawdowns(mainIdx)
#sortDrawdowns(findDrawdowns(mainIdx))

ETL(allIdx,
    p=0.099,
    method = "historical")

sigma <- M2.ewma(allIdx, lambda = 0.94)
m3    <- M3.ewma(allIdx, lambda = 0.94)
m4    <- M4.ewma(allIdx, lambda = 0.94)
#compute equal weigthe portfolio
mu <- colMeans(allIdx)
p  <- length(mu)
ES(p=0.95, portfolio_method = "component",
   weights= rep(1/p,p),
   mu= mu, sigma= sigma, m3=m3, m4=m4)

FamaBeta(allIdx,
         oneBench)

Frequency(mainIdx)
frequency(mainIdx)

HurstIndex(mainIdx) # 1 persistent, 0.5 random, 0 mean reverting



summary((exp(allIdx)-1) * 100)[,-1]
```

Portrait:
## some graphs 

graphs:

```{r graphs, echo=FALSE}

chart.ACF(mainIdx)
chart.ACFplus(mainIdx)

chart.Bar(mainIdx)
charts.Bar(allIdx, main="Returns")

chart.BarVaR(mainIdx)

chart.BarVaR(mainIdx,
             methods="HistoricalVaR")

chart.BarVaR(mainIdx,
             methods= "GaussianVaR",
             all=TRUE, lty=, lwd=2, colorset=c("red", rep("gray",2)))

chart.BarVaR(mainIdx,
             methods=c("HistoricalVaR", "ModifiedVaR", "GaussianVaR"))

chart.BarVaR(mainIdx,
             methods=c("HistoricalVaR", "ModifiedVaR", "GaussianVaR"),
             lwd=2, ypad=.01)

chart.BarVaR(mainIdx,
             methods=c("HistoricalVaR", "ModifiedVaR", "GaussianVaR"),
             lwd=2, ypad=.01, clean="boudt")

chart.BarVaR(mainIdx,
             methods="ModifiedVaR",
             lwd=2, ypad=.01, clean="boudt", show.horizontal = TRUE, lty=2)

chart.Boxplot(allIdx)
chart.Boxplot(allIdx,
              as.Tufte = TRUE)

chart.CaptureRatios(allIdx, 
                    oneBench)


chart.Correlation(allIdx,
                  histogram=TRUE)

chart.CumReturns(allIdx,
                 legend.loc="topleft")

chart.Drawdown(allIdx,
               legend.loc="bottomleft")


chart.ECDF(mainIdx)

n <- table.Drawdowns(mainIdx)
chart.Events(Drawdowns(mainIdx),
             dates= n$Trough,
             prior=max(na.omit(n$`To Trough`)),
             post=max(na.omit(n$Recovery)),
             lwd=2, xaxis=TRUE,  legend.loc="bottomleft")


chart.Histogram(mainIdx,
                breaks=40,
                methods= c("add.density", "add.rug",
                           "add.centered",
                           "add.risk", "add.qqplot"),
                show.outliers = TRUE)

# QQplot
chart.QQPlot(mainIdx,
             line=c("quartiles"),
             distribution= "norm")

library(MASS)
x <- checkData(mainIdx, na.rm=TRUE, method="vector")
fit= fitdistr(1+x, "lognormal")
chart.QQPlot(1+x, main="log-normal distrivbution", 
             envelope=0.95,
             distribution="lnorm", 
             distributionParameter = 'meanlog = fit$estimate[[1]], sdlog= fit$estimate[[2]]')

library(nor1mix)
obj= norMixEM(x, m=2)
chart.QQPlot(x, main="normal mixture distribution",
             envelope=0.95,
             line=c("quartiles"),
             distribution="norMix", 
             distributionParameter = 'obj')


library(sn)
n <- length(x)
fit.tSN <- st.mple(as.matrix(rep(1,n)), x, symmetr=TRUE)
names(fit.tSN$dp) <- c("location", "scale", "dof")
round(fit.tSN$dp, 3)
chart.QQPlot(x, main="MO Symmetric t-Distribution",
             xlab="qunatilesSymmetricTdistEst",
             envelope=0.95,
             line=c("quartiles"),
             distribution="t", 
             distributionParameter = 'df=fit.tSN$dp[3]',
             pch=20)

fit.st <- st.mple(as.matrix(rep(1,n)), x)
names(fit.st$dp) <- c("location", "scale", "skew", "dof")
round(fit.st$dp, 3)
chart.QQPlot(x, main="MO Returns Skewed t-Distribution",
             xlab="qunatilesSkewedTdistEst",
             envelope=0.95,
             line=c("quartiles"),
             distribution="st", 
             distributionParameter = 'xi = fit.st$dp[1], 
                                omega= fit.st$dp[2],
                                alpha= fit.st$dp[3],
                                nu= fit.st$dp[4]',
             pch=20)


chart.Regression(allIdx,
                 oneBench,
                 riskFree,
                 excess.return=TRUE,
                 fit= c("loess", "linear"),
                 legend.loc= "bottomright")

chart.RelativePerformance(allIdx,
                          oneBench,
                          colorset=rich8equal,
                          legend.loc="bottomleft",
                          main="Relative Performance to SXXP")

chart.RiskReturnScatter(allIdx,
                        mean(riskFree),
                        add.boxplots= FALSE)

chart.RollingCorrelation(allIdx,
                         oneBench,
                         width=100,
                         legend.loc="bottomright")

chart.RollingMean(mainIdx,
                  width=100,
                  legend.loc="bottomright")

chart.RollingPerformance(allIdx,
                         width=30,
                         legend.loc="bottomleft")

chart.RollingRegression(allIdx,
                        oneBench,
                        width=30,
                        legend.loc="bottomleft")


chart.RollingQuantileRegression(allIdx,
                                oneBench,
                                width=30,
                                legend.loc="bottomleft")

chart.Scatter(mainIdx,
              oneBench)

chart.SnailTrail(allIdx,
                 rf=riskFree,
                 width=20, stepsize=5,
                 add.names="firstandlast")

chart.StackedBar(allIdx)

chart.TimeSeries(exp(cumsum(mainIdx)))


chart.VaRSensitivity(mainIdx)    

charts.PerformanceSummary(allIdx,
                          riskFree,
                          methods="StdDev") 

charts.PerformanceSummary(allIdx)

charts.RollingPerformance(allIdx,
                          riskFree,
                          width=100,
                          legend.loc="topleft")

```

